### ISSUE TITLE
Uhh

### ISSUE THREAD

**Issue by ghost** [xproot/Workbench1CSS#1]
So I was hoping I could use this as a new workbench, but there are no useful files. Please help me?

Salutations,
- Toxidation2

**Comment by xproot** [comment]
This was already known of, but is low priority, we will take ages to fix this.

**Comment by xproot** [comment]
Fuck

**Comment by ghost** [comment]
> This was already known of, but is low priority, we will take ages to fix this.

NO, I NEED IT NOW! My old workbench is falling apart and I ran out of money to buy a new one. So I was hoping I could use this to get a free one.

**Comment by xproot** [comment]
I'm sorry but I cannot assist you in that.
